default_language_version:
  python: python3

repos:
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: python -m ruff check src tests
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: python -m mypy src/netblackbox
        language: system
        pass_filenames: false
